//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5485
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.5485.
// 
#pragma warning disable 1591

namespace UsernameAssertionClient.WseSample {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceSoap", Namespace="http://company.com/samples/wse/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SecureSoapHeader))]
    public partial class Service : Microsoft.Web.Services3.WebServicesClientProtocol
    {
        
        private BankAccountSettings bankAccountSettingsValueField;
        
        private System.Threading.SendOrPostCallback CheckAccountStatusOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service() {
            this.Url = global::UsernameAssertionClient.Properties.Settings.Default.UsernameAssertionClient_WseSample_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public BankAccountSettings BankAccountSettingsValue {
            get {
                return this.bankAccountSettingsValueField;
            }
            set {
                this.bankAccountSettingsValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CheckAccountStatusCompletedEventHandler CheckAccountStatusCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("BankAccountSettingsValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://company.com/samples/wse/CheckAccountStatus", RequestNamespace="http://company.com/samples/wse/", ResponseNamespace="http://company.com/samples/wse/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool CheckAccountStatus(string accountNumber) {
            object[] results = this.Invoke("CheckAccountStatus", new object[] {
                        accountNumber});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void CheckAccountStatusAsync(string accountNumber) {
            this.CheckAccountStatusAsync(accountNumber, null);
        }
        
        /// <remarks/>
        public void CheckAccountStatusAsync(string accountNumber, object userState) {
            if ((this.CheckAccountStatusOperationCompleted == null)) {
                this.CheckAccountStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckAccountStatusOperationCompleted);
            }
            this.InvokeAsync("CheckAccountStatus", new object[] {
                        accountNumber}, this.CheckAccountStatusOperationCompleted, userState);
        }
        
        private void OnCheckAccountStatusOperationCompleted(object arg) {
            if ((this.CheckAccountStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckAccountStatusCompleted(this, new CheckAccountStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5485")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://company.com/samples/wse/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://company.com/samples/wse/", IsNullable=false)]
    public partial class BankAccountSettings : SecureSoapHeader {
        
        private string pinCodeField;
        
        /// <remarks/>
        public string PinCode {
            get {
                return this.pinCodeField;
            }
            set {
                this.pinCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BankAccountSettings))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5485")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://company.com/samples/wse/")]
    public partial class SecureSoapHeader : System.Web.Services.Protocols.SoapHeader {
        
        private bool secureHeaderField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool SecureHeader {
            get {
                return this.secureHeaderField;
            }
            set {
                this.secureHeaderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")]
    public delegate void CheckAccountStatusCompletedEventHandler(object sender, CheckAccountStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckAccountStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckAccountStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591